# pyproject.toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "F2020"
version = "0.1.0"
description = "A project for solving differential equations using Taylor series."
authors = [
  { name = "Raul Gomez", email = "rgomez@tec.mx" }
]
dependencies = [
  "numpy",
  "matplotlib",
  "pyqt6",
  "scipy",
]

[project.scripts]
rc_circuit = "rc_circuit.rc_circuit_main:main"
taylor_coefficients = "taylor_coefficients.taylor_coefficients_main:main"
taylor_series = "taylor_series_solution.taylor_series_main:main"
frobenius_series = "frobenius_series_solution.frobenius_series_main:main"

